Aqui haremos los arreglos de las BD

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
hipocampo = pd.read_excel('HIPOCAMPO_AMIGDALA_ASEG_BIOMARCADORES_SUIZA.xlsx', sheet_name = None, decimal="," )
metricas = pd.read_excel('MÉTRICAS_AREAVOLCURVEESPESORUGOSI_BIOMARCCADORES_SUIZA.xlsx', sheet_name = None, decimal=",")
reporte = pd.read_excel('reporte_blind_biomarcadores_modificado.xls', sheet_name = None, decimal=",")

In [4]:
print("Hojas hipocampo")
for i in hipocampo.keys():
    print(i)
print("Hojas metricas")
for i in metricas.keys():
    print(i)
print("Hojas reporte")
for i in reporte.keys():
    print(i)

Hojas hipocampo
amygdalar-nuclei lh
amygdalar-nuclei rh
hipposubfields lh
hipposubfields rh
aseg_stats
Hoja1
Hojas metricas
aparc_area_lh
aparc_area_rh
aparc_meancurv_lh
aparc_meancurv_rh
aparc_thickness_lh
aparc_thickness_rh
aparc_volume_lh
aparc_volume_rh
log_rugosidad_lh
log_rugosidad_rh
Hojas reporte
preprocesamiento
Resumen

In [5]:
cantidad = reporte.copy()
cantidad = cantidad['preprocesamiento']['Unnamed: 5'].dropna()
cantidad.iloc[0:12]

0                   34 portadores
1                24 no portadores
2                    1 no se sabe
3                           5 DCL
4                           8 DTA
5                    18 controles
6        14 portadores eliminados
7     20 no portadores eliminados
8               15 DCL eliminados
9                6 DTA eliminados
10        18 controles eliminados
11          71 sujetos eliminados
Name: Unnamed: 5, dtype: object

In [6]:
cantidad.iloc[0:6]

0       34 portadores
1    24 no portadores
2        1 no se sabe
3               5 DCL
4               8 DTA
5        18 controles
Name: Unnamed: 5, dtype: object

In [7]:
def convert(x):
    return int(x.split(' ')[0])
total = np.sum(cantidad[0:6].map(convert))
print(f'Puede haber hasta un máximo de {total} pacientes')

Puede haber hasta un máximo de 90 pacientes

In [8]:
resumen = reporte.copy()
resumen = resumen['Resumen']
resumen

     CODIGO GRUPO       SEXO  EDAD  ESCOLARIDAD
0   SAN_001    aC   Femenino    28           11
1   SAN_004    aC  Masculino    33           11
2   SAN_008    aC   Femenino    31           13
3   SAN_015    aC   Femenino    32           14
4   SAN_021    aC  Masculino    27            9
..      ...   ...        ...   ...          ...
83  CTR_021   CTR  Masculino    56           11
84  CTR_023   CTR   Femenino    43           11
85  CTR_025   CTR  Masculino    59            6
86  CTR_027   CTR  Masculino    47           12
87  CTR_030   CTR   Femenino    46            4

[88 rows x 5 columns]

In [9]:
reporteNoElim = reporte.copy()
reporteNoElim = reporteNoElim['preprocesamiento'].iloc[:90,:5].fillna('')
reporteNoElim

      Codes    recod Código Biomarcadores Código Suiza GRUPO
0   SAN_001  SAN_001              SAN_001                  B
1   SAN_003  SAN_003              SAN_003                  A
2   SAN_004  SAN_004              SAN_004                  B
3   SAN_005  SAN_005              SAN_005                  A
4   SAN_006  SAN_006              SAN_006                  A
..      ...      ...                  ...          ...   ...
85  CTR_021
86  CTR_023
87  CTR_025
88  CTR_027
89  CTR_030

[90 rows x 5 columns]

In [10]:
reporteNoElimS = reporteNoElim[reporteNoElim['Código Suiza'] != '']
reporteNoElimS

        Codes    recod Código Biomarcadores Código Suiza GRUPO
38  SANS_S089  SAN_073              SAN_073         S089     A
39  SANS_S100  SAN_074              SAN_074         S100     A
40  SANS_S101  SAN_075              SAN_075         S101     B
41  SANS_S106  SAN_076              SAN_076         S106     B
42  SANS_S107  SAN_077              SAN_077         S107     B
43  SANS_S105  SAN_078              SAN_078         S105     B
44  SANS_S082  SAN_079              SAN_079         S082     A
45  SANS_S086  SAN_080              SAN_080         S086     B
46  SANS_S087  SAN_081              SAN_081         S087     B
47  SANS_S083  SAN_082              SAN_082         S083     B
48  SANS_S090  SAN_083              SAN_083         S090     B
49  SANS_S093  SAN_084              SAN_084         S093     B
50  SANS_S080  SAN_085              SAN_085         S080     B
51  SANS_S067  SAN_086              SAN_086         S067     B
52  SANS_S056  SAN_087              SAN_087         S056     A
53  SANS_S092  SAN_089              SAN_089         S092     B
54  SANS_S094  SAN_090              SAN_090         SO94     B
55  SANS_S096  SAN_091              SAN_091         S096     B
56  SANS_S097  SAN_092              SAN_092         S097     B
57  SANS_S095  SAN_093              SAN_093         S095     B
58  SANS_S108  SAN_094              SAN_094         S108     A
59  SANS_S104  SAN_095              SAN_095         S104     B

In [11]:
resumenSans = resumen[(resumen.GRUPO == "aC") | (resumen.GRUPO == "nC")]
print(resumenSans.shape)
resumenSans.head()

(58, 5)

    CODIGO GRUPO       SEXO  EDAD  ESCOLARIDAD
0  SAN_001    aC   Femenino    28           11
1  SAN_004    aC  Masculino    33           11
2  SAN_008    aC   Femenino    31           13
3  SAN_015    aC   Femenino    32           14
4  SAN_021    aC  Masculino    27            9

In [12]:
hoja1 = hipocampo['amygdalar-nuclei lh']
hoja1

,Measure:volume,Lateral-nucleus,Basal-nucleus,Accessory-Basal-nucleus,Anterior-amygdaloid-area-AAA,Central-nucleus,Medial-nucleus,Cortical-nucleus,Corticoamygdaloid-transitio,Paralaminar-nucleus,Whole_amygdala
0,CTR_001/,6.278181e+02,4.170133e+02,2.425152e+02,4.954774e+01,3.940475e+01,1.342333e+01,2.290474e+01,1.538930e+02,4.722978e+01,1.613750e+03
1,CTR_006/,5.789891e+02,3.798405e+02,2.550422e+02,4.248559e+01,3.628293e+01,1.638205e+01,2.704375e+01,1.666038e+02,4.304777e+01,1.545718e+03
2,CTR_008/,5.653896e+02,4.055797e+02,2.412015e+02,4.647498e+01,3.543857e+01,1.867795e+01,2.191914e+01,1.573719e+02,4.530344e+01,1.537357e+03
3,CTR_009/,6.238758e+02,4.079157e+02,2.420850e+02,4.621515e+01,3.914487e+01,1.329256e+01,2.214926e+01,1.509123e+02,4.606608e+01,1.591657e+03
4,CTR_010/,5.567733e+02,3.438448e+02,1.983749e+02,3.866194e+01,2.576831e+01,1.007607e+01,1.769619e+01,1.365512e+02,3.752263e+01,1.365269e+03
...,...,...,...,...,...,...,...,...,...,...,...
91,SAN_055,7.241592e+08,4.867678e+08,2.909467e+08,6.123554e+07,3.732774e+07,1.354700e+07,2.865930e+07,1.881081e+08,5.560036e+07,1.886352e+09
92,S_S031,6.368644e+08,3.766628e+08,2.095703e+08,5.096020e+07,3.344205e+07,1.194792e+07,1.894761e+07,1.381283e+08,4.280994e+07,1.519333e+09
93,S_S032,5.276715e+08,3.528467e+08,1.840704e+08,3.809287e+07,2.505587e+07,1.036522e+07,1.482954e+07,1.377293e+08,4.579427e+07,1.336456e+09
94,S_S034,5.516608e+08,3.828089e+08,2.209718e+08,4.015917e+07,3.372859e+07,1.047818e+07,1.715573e+07,1.442310e+08,4.505252e+07,1.446247e+09
95,S_S035,4.472969e+08,2.823534e+08,1.605234e+08,3.149075e+07,2.429026e+07,9.676690e+06,1.295984e+07,1.175448e+08,3.430540e+07,1.120441e+09

In [13]:
sans = hoja1[hoja1['Measure:volume'].str.startswith('S')]
sans['Measure:volume'] = sans['Measure:volume'].map(lambda x: x.split('/')[0])
print(sans.shape)
sans.head()

(57, 11)

,Measure:volume,Lateral-nucleus,Basal-nucleus,Accessory-Basal-nucleus,Anterior-amygdaloid-area-AAA,Central-nucleus,Medial-nucleus,Cortical-nucleus,Corticoamygdaloid-transitio,Paralaminar-nucleus,Whole_amygdala
30,SAN_003,572.927801,380.525824,235.786887,46.738231,38.313081,16.499223,22.151812,162.749583,40.721216,1516.413659
31,SAN_004,655.765495,487.284893,289.692331,64.024392,47.357962,16.612015,27.028990,185.462979,54.935744,1828.164800
32,SAN_005,545.865943,403.296697,241.920882,49.639985,37.504828,11.005514,22.597191,174.895589,45.958218,1532.684846
33,SAN_015,585.189944,405.303886,242.339089,46.899337,31.662182,18.286119,22.891906,169.304808,45.770747,1567.648017
34,SAN_022,645.006740,415.255949,252.780868,51.758991,35.496842,14.095003,25.273884,173.788843,47.240046,1660.697167

Generamos los cambios con lo que hemos encontrado hasta ahora, estos cambios generados no afectarán a los pacientes Suiza.

In [14]:
cambios = open('cambios.txt', 'w')

In [15]:
for i in range(sans.shape[0]):
    fila = sans.iloc[i]
    subject = fila['Measure:volume']
        
    result = resumen[resumen.CODIGO == subject]
    if result.size == 5:
        grupo = result.GRUPO.to_numpy()[0]
        sans.iloc[i,0] = grupo
        cambios.write(f'{subject}|{grupo}\n')

In [16]:
np.unique(sans['Measure:volume'], return_counts = True)

(array(['SAN_032', 'SAN_051', 'SO83', 'S_008', 'S_047', 'S_048', 'S_049',
        'S_050', 'S_052', 'S_053', 'S_054', 'S_057', 'S_058', 'S_061',
        'S_067', 'S_080', 'S_S031', 'S_S032', 'S_S033', 'S_S034', 'S_S035',
        'S_S038', 'S_S039', 'S_S042', 'S_S043', 'S_S045', 'S_S046',
        'S_S068', 'S_S070', 'S_S077', 'S_S56', 'aC', 'nC'], dtype=object),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 14, 12],
       dtype=int64))

Como vemos todos los pacientes que quedaron fueron 2 suiza y 2 SAN que NO aparecen en la BD.

Ahora podemos trabajar con la mayoria de los que quedan, que son los pacientes Suiza.

In [17]:
preprocesamiento = reporte['preprocesamiento'].iloc[:,:4].copy()
preprocesamiento = preprocesamiento.fillna('')
preprocesamiento = preprocesamiento[preprocesamiento['Código Suiza'] != '']
preprocesamiento

        Codes    recod Código Biomarcadores Código Suiza
38  SANS_S089  SAN_073              SAN_073         S089
39  SANS_S100  SAN_074              SAN_074         S100
40  SANS_S101  SAN_075              SAN_075         S101
41  SANS_S106  SAN_076              SAN_076         S106
42  SANS_S107  SAN_077              SAN_077         S107
43  SANS_S105  SAN_078              SAN_078         S105
44  SANS_S082  SAN_079              SAN_079         S082
45  SANS_S086  SAN_080              SAN_080         S086
46  SANS_S087  SAN_081              SAN_081         S087
47  SANS_S083  SAN_082              SAN_082         S083
48  SANS_S090  SAN_083              SAN_083         S090
49  SANS_S093  SAN_084              SAN_084         S093
50  SANS_S080  SAN_085              SAN_085         S080
51  SANS_S067  SAN_086              SAN_086         S067
52  SANS_S056  SAN_087              SAN_087         S056
53  SANS_S092  SAN_089              SAN_089         S092
54  SANS_S094  SAN_090              SAN_090         SO94
55  SANS_S096  SAN_091              SAN_091         S096
56  SANS_S097  SAN_092              SAN_092         S097
57  SANS_S095  SAN_093              SAN_093         S095
58  SANS_S108  SAN_094              SAN_094         S108
59  SANS_S104  SAN_095              SAN_095         S104

In [18]:
for i in range(sans.shape[0]):
    fila = sans.iloc[i]
    subject = fila['Measure:volume']
    subjectC = ''.join(char for char in subject if char.isdigit())
    if not subjectC:
        continue
    subjectC = int(subjectC)

    busqueda = preprocesamiento[preprocesamiento['Código Suiza'].str.endswith(str(subjectC))]
    if busqueda.size == 0: 
        continue
    busqueda = busqueda['Código Biomarcadores'].to_numpy()[0]
        
    result = resumen[resumen.CODIGO == busqueda]
    if result.size == 5:
        grupo = result.GRUPO.to_numpy()[0]
        sans.iloc[i,0] = grupo
        cambios.write(f'{subject}|{grupo}\n')

cambios.close()

In [19]:
np.unique(sans['Measure:volume'], return_counts = True)

(array(['SAN_032', 'SAN_051', 'S_047', 'S_048', 'S_049', 'S_050', 'S_052',
        'S_053', 'S_054', 'S_057', 'S_058', 'S_061', 'S_S031', 'S_S032',
        'S_S033', 'S_S034', 'S_S035', 'S_S038', 'S_S039', 'S_S042',
        'S_S043', 'S_S045', 'S_S046', 'S_S068', 'S_S070', 'S_S077', 'aC',
        'nC'], dtype=object),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1, 17, 14], dtype=int64))

In [20]:
np.sum(np.unique(sans['Measure:volume'], return_counts = True)[1])-31

26

Quedó un total de 26 pacientes sin clasificar despues de esto, logrando clasificar unicamente a 5 pacientes suiza.

**BD METRICAS**

Ahora realizaremos esto para la base de datos de métricas.

In [21]:
hoja1 = metricas['aparc_area_lh']
hoja1

,lh.aparc.area,lh_caudalanteriorcingulate_area,lh_entorhinal_area,lh_isthmuscingulate_area,lh_medialorbitofrontal_area,lh_middletemporal_area,lh_parahippocampal_area,lh_posteriorcingulate_area,lh_rostralanteriorcingulate_area,BrainSegVolNotVent
0,CTR_001/,895,344,1137,1879,3080,616,989,942,1097191
1,CTR_006/,605,365,810,1444,2689,612,997,730,909285
2,CTR_008/,495,445,925,1622,2509,511,1127,571,1015293
3,CTR_009/,365,330,949,1738,2765,593,1032,763,1024225
4,CTR_010/,333,331,737,1455,2227,522,795,453,827608
...,...,...,...,...,...,...,...,...,...,...
90,S_047,696,340,1097,1919,3133,478,1243,691,1000187
91,S_048,490,329,1105,1673,2483,554,1082,886,841443
92,S_049,463,327,780,1669,2491,568,987,528,842354
93,S_050,612,352,798,1778,2661,514,962,848,965636
94,S_052,550,382,1096,1860,3222,723,1199,646,1049080

In [22]:
sans = hoja1[hoja1[hoja1.columns[0]].str.startswith('S')]
sans[hoja1.columns[0]] = sans[hoja1.columns[0]].map(lambda x: x.split('/')[0])
print(sans.shape)
sans.head()

(36, 10)

,lh.aparc.area,lh_caudalanteriorcingulate_area,lh_entorhinal_area,lh_isthmuscingulate_area,lh_medialorbitofrontal_area,lh_middletemporal_area,lh_parahippocampal_area,lh_posteriorcingulate_area,lh_rostralanteriorcingulate_area,BrainSegVolNotVent
51,SAN_071,586,376,841,1468,2681,625,1051,732,973780
52,SAN_038,676,487,958,1808,3020,529,1093,860,1200076
53,SAN_001,665,340,904,1893,2696,663,1115,642,1116877
54,SAN_030,528,496,913,1834,3033,642,1179,692,1112920
55,S_S033,486,356,803,1436,2312,524,1034,715,912550

Ahora realizamos los cambios

In [23]:
cambios = open('cambios2.txt', 'w')

In [24]:
for i in range(sans.shape[0]):
    fila = sans.iloc[i]
    subject = fila[hoja1.columns[0]]
        
    result = resumen[resumen.CODIGO == subject]
    if result.size == 5:
        grupo = result.GRUPO.to_numpy()[0]
        sans.iloc[i,0] = grupo
        cambios.write(f'{subject}|{grupo}\n')

In [25]:
np.unique(sans[hoja1.columns[0]], return_counts = True)

(array(['SO83', 'S_008', 'S_047', 'S_048', 'S_049', 'S_050', 'S_052',
        'S_053', 'S_054', 'S_057', 'S_058', 'S_061', 'S_067', 'S_080',
        'S_S031', 'S_S032', 'S_S033', 'S_S034', 'S_S035', 'S_S038',
        'S_S039', 'S_S042', 'S_S043', 'S_S045', 'S_S046', 'S_S068',
        'S_S070', 'S_S077', 'S_S56', 'aC', 'nC'], dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 4, 3], dtype=int64))

Se logró categorizar a todos los pacientes que eran considerados "SAN", ahora se hará el cambio con los pacientes de suiza.

In [26]:
for i in range(sans.shape[0]):
    fila = sans.iloc[i]
    subject = fila[hoja1.columns[0]]
    subjectC = ''.join(char for char in subject if char.isdigit())
    if not subjectC:
        continue
    subjectC = int(subjectC)

    busqueda = preprocesamiento[preprocesamiento['Código Suiza'].str.endswith(str(subjectC))]
    if busqueda.size == 0: 
        continue
    busqueda = busqueda['Código Biomarcadores'].to_numpy()[0]
        
    result = resumen[resumen.CODIGO == busqueda]
    if result.size == 5:
        grupo = result.GRUPO.to_numpy()[0]
        sans.iloc[i,0] = grupo
        cambios.write(f'{subject}|{grupo}\n')

cambios.close()

In [27]:
np.unique(sans[hoja1.columns[0]], return_counts = True)

(array(['S_047', 'S_048', 'S_049', 'S_050', 'S_052', 'S_053', 'S_054',
        'S_057', 'S_058', 'S_061', 'S_S031', 'S_S032', 'S_S033', 'S_S034',
        'S_S035', 'S_S038', 'S_S039', 'S_S042', 'S_S043', 'S_S045',
        'S_S046', 'S_S068', 'S_S070', 'S_S077', 'aC', 'nC'], dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 7, 5], dtype=int64))

En este caso se logró unicamente recuperar 12 de los pacientes en categorias aC o nC, el resto quedó sin clasificar.